#!/bin/bash
hc() {
	cmds="$cmds , $@"
}

av() {
	hash $1 2>/dev/null
}

# Emit reload hook
hc emit_hook reload

# load configs
dir=~/.config/herbstluftwm/scripts
source $dir/bindings
source $dir/tags
source $dir/theme
source $dir/windows

# Add padding
herbstclient pad 0 ${WMPADDINGY:-0} ${WMPADDINGX:-0}

# Run all commands and unlock herbstluftwm
herbstclient chain $cmds
herbstclient unlock
