#!/bin/bash
# Herbstclient config regarding colors and layout

# padding
hc set window_gap $window_gap
hc set frame_gap $frame_gap
hc set frame_padding $frame_padding

# borders / backgrounds
hc set frame_border_width $frame_border_width
hc set frame_border_inner_width $frame_border_inner_width
hc set window_border_width $window_border_width
hc set window_border_inner_width $window_border_inner_width
hc set frame_bg_transparent $frame_bg_transparent
hc set frame_transparent_width $frame_transparent_width

# colors
hc set window_border_active_color "$COLOR3"
hc set window_border_normal_color "$COLOR0"
