#!/bin/bash
# Herbstclient config regarding colors and layout

# padding
hc set window_gap                 8
hc set frame_gap                  0
hc set frame_padding              0

# borders / backgrounds
hc set frame_border_width         0
hc set frame_border_inner_width   0
hc set window_border_width        1
hc set window_border_inner_width  0
hc set frame_bg_transparent       1
hc set frame_transparent_width    0

# colors
hc set window_border_active_color $COLOR3
hc set window_border_normal_color $COLOR0
