#!/bin/bash

export Mod=Mod4

export font="terminus-10"
export terminal="urxvt"
export browser="google-chrome-stable"

export default_frame_layout=3

export frame_border_width=0
export frame_border_inner_width=0
export window_border_width=4
export window_border_inner_width=0
export frame_transparent_width=0

export window_gap=8
export frame_gap=O
export frame_padding=0

export frame_bg_transparent=1
