#!/bin/bash
hc() {
  cmds="$cmds , $@"
}

# Emit reload hook
hc emit_hook reload

# load configs
dir=~/.config/herbstluftwm/
source $dir/config
source $dir/apps

# include other autostart stuff
source $dir/bindings
source $dir/tags
source $dir/theme
source $dir/rules
source $dir/bar

herbstclient chain $cmds
herbstclient unlock
