#!/bin/bash
# Set keymap (keeps resetting for some reason)
setxkbmap de

# Set background
feh --bg-fill --no-fehbg "$(wpmanager current)"

# Set colors
cat "$(wpmanager currentx)" | xrdb -merge

# Start compton and set inactive windows to use a blurred background at 80% opacity
compton -f --no-fading-openclose -C -c -i 0.8 -b --blur-background --blur-kern 7x7box --backend glx

# Copy the current background to a location, our desktop manager (lightdm) can read it
# There HAS to be a better way to do this
sudo cp "$(wpmanager current)" /usr/share/background.png
