#!/bin/bash
# Configure any values in here

# Modifier key
export Mod=Mod4

# Font, terminal and browser settings
export font="terminus-10"
export terminal="urxvt"
export browser="google-chrome-stable"

# Herbstluftwm layout settings
export default_frame_layout=3

export frame_border_width=0
export frame_border_inner_width=0
export window_border_width=4
export window_border_inner_width=0
export frame_transparent_width=0

export window_gap=8
export frame_gap=O
export frame_padding=0

export frame_bg_transparent=1
