#!/bin/bash
# Bash script to start dmenu with given parameters

# Load colors
source "$(wpmanager currentc)"

# Define dmenu options
dmenu="/usr/bin/dmenu -i -h 32 -nb '#1f1f1f' -nf '#c0b18b' -sb '#c0b18b' -sf '#1f1f1f'"

# Start
j4-dmenu-desktop --dmenu="$dmenu"
