#!/bin/bash
# Tag definition for herbstluftwm

# enumerate tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

# Create tags and bind their keys
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
